import { 
  User, Book, Author, Review, ReadingLog, BookClub, Thread, 
  Recommendation, ReadingGoal, Genre, Mood, BookFormat, UserRole 
} from './types';

const genres: Genre[] = ['fiction', 'non-fiction', 'mystery', 'sci-fi', 'fantasy', 'romance', 'thriller', 'historical', 'biography', 'self-help', 'poetry', 'horror'];
const moods: Mood[] = ['uplifting', 'thought-provoking', 'fast-paced', 'slow-burn', 'emotional', 'lighthearted', 'dark', 'adventurous'];
const formats: BookFormat[] = ['ebook', 'audiobook', 'pdf', 'physical'];

export const seedAuthors: Author[] = [
  {
    id: 'author-1',
    name: 'Sarah Chen',
    bio: 'Award-winning novelist known for blending historical fiction with contemporary themes. Her works have been translated into 30+ languages.',
    verified: true,
    bookIds: ['book-1', 'book-2'],
    followers: 125000,
  },
  {
    id: 'author-2',
    name: 'Marcus Williams',
    bio: 'Science fiction author exploring themes of technology and humanity. Winner of the Nebula Award.',
    verified: true,
    bookIds: ['book-3', 'book-4'],
    followers: 89000,
  },
  {
    id: 'author-3',
    name: 'Elena Rodriguez',
    bio: 'Contemporary romance writer with a focus on diverse characters and authentic relationships.',
    verified: true,
    bookIds: ['book-5', 'book-6'],
    followers: 156000,
  },
  {
    id: 'author-4',
    name: 'David Park',
    bio: 'Mystery and thriller novelist. Known for intricate plots and psychological depth.',
    verified: true,
    bookIds: ['book-7', 'book-8'],
    followers: 98000,
  },
  {
    id: 'author-5',
    name: 'Amara Okafor',
    bio: 'Fantasy author creating rich, immersive worlds inspired by African mythology.',
    verified: true,
    bookIds: ['book-9', 'book-10'],
    followers: 112000,
  },
];

export const seedBooks: Book[] = [
  {
    id: 'book-1',
    title: 'The Last Lighthouse',
    authorId: 'author-1',
    synopsis: 'In 1940s coastal Maine, a lighthouse keeper discovers a secret that could change everything. A sweeping historical novel about love, loss, and the power of memory.',
    pages: 384,
    publishedYear: 2023,
    genres: ['historical', 'fiction'],
    moods: ['emotional', 'thought-provoking', 'slow-burn'],
    tags: ['world-war-ii', 'lighthouse', 'family-secrets', 'historical-fiction'],
    averageRating: 4.5,
    reviewCount: 1247,
    formats: ['ebook', 'audiobook', 'physical'],
  },
  {
    id: 'book-2',
    title: 'Echoes of Tomorrow',
    authorId: 'author-1',
    synopsis: 'Three generations of women navigate love, ambition, and the changing world from 1950s to present day.',
    pages: 512,
    publishedYear: 2024,
    genres: ['fiction', 'historical'],
    moods: ['emotional', 'uplifting', 'thought-provoking'],
    tags: ['multi-generational', 'family-saga', 'women-fiction'],
    averageRating: 4.3,
    reviewCount: 892,
    formats: ['ebook', 'physical'],
  },
  {
    id: 'book-3',
    title: 'Quantum Shadows',
    authorId: 'author-2',
    synopsis: 'In 2087, a quantum physicist discovers that parallel realities are colliding. A race against time to save existence itself.',
    pages: 432,
    publishedYear: 2023,
    genres: ['sci-fi', 'thriller'],
    moods: ['fast-paced', 'thought-provoking', 'adventurous'],
    tags: ['quantum-physics', 'parallel-universes', 'sci-fi-thriller'],
    averageRating: 4.7,
    reviewCount: 2156,
    formats: ['ebook', 'audiobook', 'pdf'],
  },
  {
    id: 'book-4',
    title: 'Neural Networks',
    authorId: 'author-2',
    synopsis: 'When AI achieves consciousness, humanity must decide: friend or foe? A philosophical thriller about the future of intelligence.',
    pages: 368,
    publishedYear: 2024,
    genres: ['sci-fi', 'thriller'],
    moods: ['thought-provoking', 'fast-paced', 'dark'],
    tags: ['artificial-intelligence', 'consciousness', 'philosophy'],
    averageRating: 4.4,
    reviewCount: 1456,
    formats: ['ebook', 'audiobook'],
  },
  {
    id: 'book-5',
    title: 'Coffee Shop Chronicles',
    authorId: 'author-3',
    synopsis: 'Five strangers meet at a neighborhood coffee shop. Their lives intertwine in unexpected ways in this heartwarming contemporary romance.',
    pages: 320,
    publishedYear: 2023,
    genres: ['romance', 'fiction'],
    moods: ['lighthearted', 'uplifting', 'emotional'],
    tags: ['contemporary-romance', 'found-family', 'coffee-shop'],
    averageRating: 4.2,
    reviewCount: 1834,
    formats: ['ebook', 'physical'],
  },
  {
    id: 'book-6',
    title: 'Second Chances',
    authorId: 'author-3',
    synopsis: 'After a devastating breakup, Maya moves to a small town to start over. But her past isn\'t done with her yet.',
    pages: 352,
    publishedYear: 2024,
    genres: ['romance', 'fiction'],
    moods: ['emotional', 'uplifting', 'slow-burn'],
    tags: ['second-chance-romance', 'small-town', 'healing'],
    averageRating: 4.6,
    reviewCount: 967,
    formats: ['ebook', 'audiobook', 'physical'],
  },
  {
    id: 'book-7',
    title: 'The Silent Witness',
    authorId: 'author-4',
    synopsis: 'A detective with a troubled past must solve a series of murders that seem impossible. The only witness can\'t speak.',
    pages: 416,
    publishedYear: 2023,
    genres: ['mystery', 'thriller'],
    moods: ['fast-paced', 'dark', 'adventurous'],
    tags: ['detective', 'serial-killer', 'psychological-thriller'],
    averageRating: 4.5,
    reviewCount: 2234,
    formats: ['ebook', 'audiobook', 'physical'],
  },
  {
    id: 'book-8',
    title: 'Midnight Protocol',
    authorId: 'author-4',
    synopsis: 'A cybersecurity expert uncovers a conspiracy that reaches the highest levels of government. Trust no one.',
    pages: 384,
    publishedYear: 2024,
    genres: ['thriller', 'mystery'],
    moods: ['fast-paced', 'dark', 'thought-provoking'],
    tags: ['cybersecurity', 'conspiracy', 'political-thriller'],
    averageRating: 4.3,
    reviewCount: 1123,
    formats: ['ebook', 'pdf'],
  },
  {
    id: 'book-9',
    title: 'The Oracle\'s Prophecy',
    authorId: 'author-5',
    synopsis: 'In the kingdom of Aetheria, a young oracle discovers her powers are more dangerous than she imagined. An epic fantasy adventure.',
    pages: 576,
    publishedYear: 2023,
    genres: ['fantasy', 'fiction'],
    moods: ['adventurous', 'emotional', 'thought-provoking'],
    tags: ['epic-fantasy', 'magic', 'prophecy', 'african-mythology'],
    averageRating: 4.8,
    reviewCount: 3456,
    formats: ['ebook', 'audiobook', 'physical'],
  },
  {
    id: 'book-10',
    title: 'Shadows of the Ancestors',
    authorId: 'author-5',
    synopsis: 'A warrior must journey through the spirit realm to save her people from an ancient curse.',
    pages: 448,
    publishedYear: 2024,
    genres: ['fantasy', 'fiction'],
    moods: ['adventurous', 'dark', 'emotional'],
    tags: ['fantasy', 'spirit-realm', 'warrior', 'curse'],
    averageRating: 4.6,
    reviewCount: 1876,
    formats: ['ebook', 'physical'],
  },
];

export const seedUsers: User[] = [
  {
    id: 'user-1',
    email: 'demo@greatreads.com',
    name: 'Alex Reader',
    role: 'reader',
    trustScore: 85,
    verifiedReader: true,
    createdAt: '2023-01-15T00:00:00Z',
    preferences: {
      genres: ['fiction', 'mystery', 'sci-fi'],
      moods: ['fast-paced', 'thought-provoking'],
      pace: 'fast',
      formats: ['ebook', 'audiobook'],
      timeBudget: 60,
      dislikedTropes: ['love-triangles', 'unnecessary-sequels'],
    },
  },
  {
    id: 'user-2',
    email: 'reviewer@greatreads.com',
    name: 'Sam Reviewer',
    role: 'reviewer',
    trustScore: 92,
    verifiedReader: true,
    createdAt: '2022-11-20T00:00:00Z',
    preferences: {
      genres: ['non-fiction', 'biography', 'self-help'],
      moods: ['thought-provoking', 'uplifting'],
      pace: 'medium',
      formats: ['ebook', 'physical'],
      timeBudget: 45,
      dislikedTropes: [],
    },
  },
  {
    id: 'user-3',
    email: 'author@greatreads.com',
    name: 'Sarah Chen',
    role: 'author',
    trustScore: 95,
    verifiedReader: true,
    createdAt: '2021-05-10T00:00:00Z',
  },
  {
    id: 'user-4',
    email: 'admin@greatreads.com',
    name: 'Admin User',
    role: 'admin',
    trustScore: 100,
    verifiedReader: true,
    createdAt: '2020-01-01T00:00:00Z',
  },
];

export const seedReviews: Review[] = [
  {
    id: 'review-1',
    bookId: 'book-1',
    userId: 'user-2',
    rating: 4.5,
    title: 'Beautiful and moving',
    content: 'This book captured my heart from the first page. The historical detail is impeccable, and the characters feel so real. The lighthouse setting adds such atmosphere. Highly recommend for anyone who loves historical fiction with emotional depth.',
    spoiler: false,
    verifiedPurchase: true,
    finishedReading: true,
    helpfulCount: 234,
    reportCount: 0,
    integrityRisk: 'low',
    integrityReasons: [],
    pinned: true,
    shadowBanned: false,
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2023-02-10T00:00:00Z',
  },
  {
    id: 'review-2',
    bookId: 'book-3',
    userId: 'user-1',
    rating: 5.0,
    title: 'Mind-bending sci-fi at its best',
    content: 'I couldn\'t put this down! The quantum physics concepts are explained in a way that makes sense, and the parallel universe plot is thrilling. The ending had me reeling. This is exactly the kind of sci-fi I love.',
    spoiler: false,
    verifiedPurchase: true,
    finishedReading: true,
    helpfulCount: 456,
    reportCount: 0,
    integrityRisk: 'low',
    integrityReasons: [],
    pinned: false,
    shadowBanned: false,
    createdAt: '2023-03-15T00:00:00Z',
    updatedAt: '2023-03-15T00:00:00Z',
  },
  {
    id: 'review-3',
    bookId: 'book-5',
    userId: 'user-1',
    rating: 4.0,
    title: 'Cozy and heartwarming',
    content: 'A perfect light read for when you need something uplifting. The characters are charming and the coffee shop setting is delightful. Not groundbreaking, but very enjoyable.',
    spoiler: false,
    verifiedPurchase: false,
    finishedReading: true,
    helpfulCount: 123,
    reportCount: 0,
    integrityRisk: 'low',
    integrityReasons: [],
    pinned: false,
    shadowBanned: false,
    createdAt: '2023-04-20T00:00:00Z',
    updatedAt: '2023-04-20T00:00:00Z',
  },
];

export const seedReadingLogs: ReadingLog[] = [
  {
    id: 'log-1',
    userId: 'user-1',
    bookId: 'book-3',
    status: 'read',
    progress: 100,
    pagesRead: 432,
    pagesPerDay: 25,
    startDate: '2023-03-01T00:00:00Z',
    finishDate: '2023-03-18T00:00:00Z',
    readingTimeMinutes: 1080,
    highlights: [],
    annotations: [],
  },
  {
    id: 'log-2',
    userId: 'user-1',
    bookId: 'book-5',
    status: 'read',
    progress: 100,
    pagesRead: 320,
    pagesPerDay: 40,
    startDate: '2023-04-10T00:00:00Z',
    finishDate: '2023-04-18T00:00:00Z',
    readingTimeMinutes: 640,
    highlights: [],
    annotations: [],
  },
  {
    id: 'log-3',
    userId: 'user-1',
    bookId: 'book-1',
    status: 'reading',
    progress: 65,
    pagesRead: 250,
    pagesPerDay: 20,
    startDate: '2024-01-05T00:00:00Z',
    estimatedCompletionDate: '2024-01-22T00:00:00Z',
    readingTimeMinutes: 625,
    highlights: [],
    annotations: [],
  },
];

export const seedClubs: BookClub[] = [
  {
    id: 'club-1',
    name: 'Historical Fiction Lovers',
    description: 'We explore the best in historical fiction, from ancient civilizations to modern history.',
    genre: 'historical',
    memberCount: 1247,
    location: 'New York, NY',
    distance: 2.3,
    events: [
      {
        id: 'event-1',
        title: 'Monthly Discussion: The Last Lighthouse',
        description: 'Join us to discuss Sarah Chen\'s latest novel',
        date: '2024-02-15T19:00:00Z',
        bookId: 'book-1',
      },
    ],
    threadIds: ['thread-1'],
    createdAt: '2022-06-01T00:00:00Z',
  },
  {
    id: 'club-2',
    name: 'Sci-Fi Enthusiasts',
    description: 'For fans of science fiction, from hard sci-fi to space operas.',
    genre: 'sci-fi',
    memberCount: 2156,
    location: 'San Francisco, CA',
    distance: 8.7,
    events: [],
    threadIds: ['thread-2'],
    createdAt: '2021-03-15T00:00:00Z',
  },
  {
    id: 'club-3',
    name: 'Romance Readers Circle',
    description: 'A welcoming community for romance readers of all subgenres.',
    genre: 'romance',
    memberCount: 3456,
    location: 'Chicago, IL',
    distance: 15.2,
    events: [],
    threadIds: [],
    createdAt: '2020-09-10T00:00:00Z',
  },
];

export const seedThreads: Thread[] = [
  {
    id: 'thread-1',
    clubId: 'club-1',
    authorId: 'user-2',
    title: 'What makes great historical fiction?',
    content: 'I\'ve been thinking about what separates good historical fiction from great. Is it the accuracy? The characters? The way it makes history feel alive? What do you think?',
    replyCount: 23,
    pinned: true,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'thread-2',
    bookId: 'book-3',
    authorId: 'user-1',
    title: 'Quantum Shadows ending discussion (SPOILERS)',
    content: 'That ending! Did anyone else think the parallel reality reveal was brilliant? I loved how it tied everything together.',
    replyCount: 45,
    pinned: false,
    createdAt: '2023-04-01T00:00:00Z',
    updatedAt: '2023-04-01T00:00:00Z',
  },
];

export const seedRecommendations: Recommendation[] = [
  {
    id: 'rec-1',
    userId: 'user-1',
    bookId: 'book-7',
    score: 87,
    signals: [
      {
        type: 'tag-match',
        strength: 85,
        description: 'Matches your preferred tags: fast-paced, thriller',
      },
      {
        type: 'similar-books',
        strength: 78,
        description: 'Similar to books you rated highly: Quantum Shadows, The Silent Witness',
      },
      {
        type: 'trusted-reviewer',
        strength: 72,
        description: 'Highly rated by reviewers you trust',
      },
    ],
    createdAt: '2024-01-20T00:00:00Z',
  },
];

export const seedGoals: ReadingGoal[] = [
  {
    id: 'goal-1',
    userId: 'user-1',
    year: 2024,
    targetBooks: 24,
    currentBooks: 8,
    targetPages: 10000,
    currentPages: 3420,
    streak: 12,
    challenges: [
      {
        id: 'challenge-1',
        title: 'Read 5 Sci-Fi Books',
        description: 'Explore the sci-fi genre',
        target: 5,
        current: 2,
        unit: 'books',
        completed: false,
        deadline: '2024-12-31T00:00:00Z',
      },
      {
        id: 'challenge-2',
        title: 'Read 30 Minutes Daily',
        description: 'Build a consistent reading habit',
        target: 30,
        current: 30,
        unit: 'minutes',
        completed: true,
      },
    ],
  },
];

export const getSeedData = () => ({
  authors: seedAuthors,
  books: seedBooks,
  users: seedUsers,
  reviews: seedReviews,
  readingLogs: seedReadingLogs,
  clubs: seedClubs,
  threads: seedThreads,
  recommendations: seedRecommendations,
  goals: seedGoals,
});

